version: "3.3"
services:
  front-end: 
    image: vunguyenvu35/laravel-on-k8s:v4
    volumes:
      - /opt/mss/BSS_HK_Front:/usr/local/apache2/htdocs/app
    ports:
      - '80:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.10
  common: 
    image: vunguyenvu35/laravel-on-k8s:v4
    volumes:
      - /opt/mss/BSS_Common_Services:/usr/local/apache2/htdocs/app
    networks:
      gau_net:
        ipv4_address: 172.16.238.11
    ports:
      - '11:80'
  media: 
    image: vunguyenvu35/laravel-on-k8s:v4
    volumes:
      - /opt/mss/BSS_Media_Services:/usr/local/apache2/htdocs/app
    ports:
      - '12:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.12
    ports:
      - '12:80'
  post: 
    image: vunguyenvu35/laravel-on-k8s:v4
    volumes:
      - /opt/mss/BSS_Post_Services:/usr/local/apache2/htdocs/app
    networks:
      gau_net:
        ipv4_address: 172.16.238.13
    ports:
      - '13:80'
  shop: 
    image: vunguyenvu35/laravel-on-k8s:v4
    volumes:
      - /opt/mss/BSS_Shop_Services:/usr/local/apache2/htdocs/app
    ports:
      - '14:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.14
  thumbor: 
    image: apsl/thumbor
    ports:
      - '8000:8000'
    ports:
      - '15:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.15
  customer: 
    image: vunguyenvu35/laravel-on-k8s:v4
    volumes:
      - /opt/mss/BSS_Customer_Services:/usr/local/apache2/htdocs/app
    ports:
      - '16:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.16
  search: 
    image: vunguyenvu35/laravel-on-k8s:v4
    volumes:
      - /opt/mss/BSS_Search_Services:/usr/local/apache2/htdocs/app
    ports:
      - '17:80'
    networks:
      gau_net:
        ipv4_address: 172.16.238.17

################################################################################
# NETWORK
################################################################################
networks:
  gau_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
   